
server:
  port: 8761

spring:
  application:
    name: hatech-center-eureka

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port} # 以[IP地址:端口号]作为注册地址
    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒，如果要迅速获取服务注册状态，可以缩小该值
    lease-renewal-interval-in-seconds: 5
    # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    # 默认为90秒
    # 如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。
    # 如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。
    # 该值至少应该大于 leaseRenewalIntervalInSeconds
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false #默认为true，设置为false，仅作为服务中心，不作为服务客户端
    fetch-registry: false #默认为true，设置为false， 不从服务中心检索注册的服务
  server:
    eviction-interval-timer-in-ms: 5000 #清理间隔（单位毫秒， 默认是60*1000）
    enable-self-preservation: false #默认为true，设置为false，关闭自我保护
    #指定每分钟需要收到的续约次数阈值，默认是0.85
    renewal-percent-threshold: 0.49
    response-cache-auto-expiration-in-seconds: 60 # 默认是180，调整缓存过期更新时间


logging:
  level:
    cn.com.hatechframework: debug
  file:
    path: ./log/${spring.application.name}/${spring.application.name}.log

